version: 2.1

executors:
  python:
    working_directory: ~/slack_user_avatar_emojis
    docker:
      - image: python:3.6
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          LANG: ja_JP.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: ja_JP.UTF-8

commands:
  install-git-submodule:
    steps:
      - run:
          name: Install submodule
          command: |
            git submodule sync
            git submodule update --init
  install-python-dependencies:
    steps:
      - run:
          name: Install python dependencies
          command: |
            python -V
            cd slack-emojinator
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
  install-os-dependencies:
    steps:
      - run:
          name: Update apt-get
          command: apt-get update
      - run:
          name: Install jq
          command: apt-get install -y jq

jobs:
  build:
    executor:
      name: python
    steps:
      - checkout
      - install-os-dependencies
      - install-git-submodule
      - install-python-dependencies
      - run:
          name: Execute registring emoji
          command: ./run.sh

  register-emoji:
    executor:
      name: python
    steps:
      - checkout
      - install-os-dependencies
      - install-git-submodule
      - install-python-dependencies

      - run:
          name: Execute registring emoji
          command: ./run.sh

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  nightly-workflow:
    triggers:
      - schedule:
          cron: "00 * * * *" # UTC (JST +9)
          filters:
            branches:
              only:
                - master
    jobs:
      - register-emoji
